import { library, dom } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { faUsb } from '@fortawesome/free-brands-svg-icons'
import {
  faArrowRight,
  faBars,
  faChartLine,
  faCheck,
  faCheckCircle,
  faClock,
  faCloudDownloadAlt,
  faEthernet,
  faExchangeAlt,
  faExternalLinkAlt,
  faEye,
  faEyeSlash,
  faGaugeHigh,
  faGlobe,
  faHardDrive,
  faHeartbeat,
  faMemory,
  faMicrochip,
  faMobileAlt,
  faMoon,
  faPuzzlePiece,
  faQuestionCircle,
  faSignOutAlt,
  faSliders,
  faSpinner,
  faStar,
  faSun,
  faSyncAlt,
  faTemperatureHalf,
  faTerminal,
  faTimesCircle,
  faTowerBroadcast,
  faTowerCell,
  faTrash,
  faTriangleExclamation,
  faEnvelope
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faArrowRight,
  faBars,
  faChartLine,
  faCheck,
  faCheckCircle,
  faClock,
  faCloudDownloadAlt,
  faEthernet,
  faExchangeAlt,
  faExternalLinkAlt,
  faEye,
  faEyeSlash,
  faGaugeHigh,
  faGlobe,
  faHardDrive,
  faHeartbeat,
  faMemory,
  faMicrochip,
  faMobileAlt,
  faMoon,
  faPuzzlePiece,
  faQuestionCircle,
  faSignOutAlt,
  faSliders,
  faSpinner,
  faStar,
  faSun,
  faSyncAlt,
  faTemperatureHalf,
  faTerminal,
  faTimesCircle,
  faTowerBroadcast,
  faTowerCell,
  faTrash,
  faTriangleExclamation,
  faEnvelope,
  faUsb
)

dom.watch()

export { FontAwesomeIcon }
